### ISSUE TITLE
Code does not meet requirements

### ISSUE THREAD

**Issue by ecoppen** [Elgun1234/Programming-challenges#6]
This code doesn't meet the brief:
![Screenshot 2022-09-09 170852](https://user-images.githubusercontent.com/51025241/189394164-3e3896c3-8693-4d51-9623-d1c58592cf67.png)

You'll need to make a table like that, to do the padding reference here: https://saralgyaan.com/posts/f-string-in-python-usage-guide/#How_to_add_space_padding_in_Python_f-strings?

By contrast yours does this currently: 

![Screenshot 2022-09-09 170945](https://user-images.githubusercontent.com/51025241/189394324-32c0e744-a8f2-4f1f-acfd-1730ac4cf70c.png)

**Comment by Elgun1234** [comment]
the padding in new code for the heading goes to the right while the padding for everything else goes to the left.  why?
